{
 "title": "Hubble Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Sync %",
   "type": "stat",
   "description": "Percentage of FC messages in local hub relative to last known peer. May fluctuate as peers change.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.syncengine.sync_percent"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(stats.gauges.hubble.gossip.peers.*)"
    }
   ]
  },
  {
   "title": "Blocks Processed",
   "type": "timeseries",
   "description": "Number of blocks being processed for Farcaster Contract events",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "stats_counts.hubble.ethevents.blocks"
    },
    {
     "target": "stats_counts.hubble.l2events.blocks"
    }
   ]
  },
  {
   "title": "Farcaster Messages",
   "type": "timeseries",
   "description": "Number of Farcaster Messages stored in the DB. Increases and decreases when users add or delete data.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "target": "stats.gauges.hubble.merkle_trie.num_messages"
    }
   ]
  },
  {
   "title": "Protocol Version",
   "type": "stat",
   "description": "The Farcaster Protocol version.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.hubble.farcaster.fcversion.*, 5)"
    }
   ]
  },
  {
   "title": "App Version",
   "type": "stat",
   "description": "The Hubble App version ",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.hubble.farcaster.appversion.*, 5)"
    }
   ]
  },
  { "title": "Sync Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Incoming Gossip",
   "type": "timeseries",
   "description": "Number of gossip messages received from peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "target": "stats_counts.hubble.gossip.*.*" }
   ]
  },
  {
   "title": "Inbound Gossip Connections",
   "type": "gauge",
   "description": "Peers with open inbound connections. Requires port 2282 to be open. Gossip works even without inbound connections, but not having any may affect your peer score and network health. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.gossip.peers.inbound"
    }
   ]
  },
  {
   "title": "Gossip Peers",
   "type": "timeseries",
   "description": "Number of peers that Hubble is connected with for outbound and inbound flow.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "target": "stats.gauges.hubble.gossip.peers.inbound"
    },
    {
     "target": "stats.gauges.hubble.gossip.peers.outbound"
    },
    {
     "target": "stats.gauges.hubble.peer_store.count"
    }
   ]
  },
  {
   "title": "Sync Duration",
   "type": "timeseries",
   "description": "Time taken to perform a diff sync which fetches all unknown messages from a peer over grpc.  Happens every two minutes unless a sync is already running. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "target": "stats.timers.hubble.syncengine.sync_time_ms.sum"
    }
   ]
  },
  {
   "title": "Inbound Sync Attempts",
   "type": "gauge",
   "description": "Successful inbound syncs from peers. Requires port 2283 to be open. Outbound sync works even if the port is closed but it may affect your peer reputation score and network health. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "stats_counts.hubble.rpc.get_sync_snapshot"
    }
   ]
  },
  {
   "title": "Blocked Peers",
   "type": "gauge",
   "description": "Number of peers blocked due to bad peer reputation scores.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.hubble.gossip.denied_peers"
    }
   ]
  },
  { "title": "Perf Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Merge Latency",
   "type": "timeseries",
   "description": "Time taken to merge a newly received message into the Hub's DB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "stats.timers.hubble.hub.merge_message.mean"
    }
   ]
  },
  {
   "title": "Merge Queue Size",
   "type": "timeseries",
   "description": "Number of messages waiting in queue to be merged",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "stats.gauges.hubble.syncengine.merge_q"
    }
   ]
  },
  {
   "title": "Merkle Trie Queue Size",
   "type": "timeseries",
   "description": "Number of messages waiting to be added to the merkle sync trie.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "stats.gauges.hubble.merkle_trie.merge_q"
    }
   ]
  },
  {
   "title": "DB Size on disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.hubble.rocksdb.approximate_size"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.hubble.memory.external"
    },
    {
     "target": "stats.gauges.hubble.memory.heap_total"
    },
    {
     "target": "stats.gauges.hubble.memory.heap_used"
    },
    { "target": "stats.gauges.hubble.memory.rss" }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Errors by Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "target": "sumSeriesWithWildcards(stats_counts.hubble.submit_message.error.*.*.*, 5,6)"
    }
   ]
  },
  {
   "title": "Errors by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "target": "sumSeriesWithWildcards(stats_counts.hubble.submit_message.error.*.*.*, 4,5)"
    }
   ]
  },
  { "title": "Sync Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Sync Merge Results",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 61 },
   "targets": [
    {
     "target": "aliasByNode(stats_counts.hubble.syncengine.sync_messages.*, 3, 4)"
    }
   ]
  },
  {
   "title": "Peer Sync Timings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.hubble.syncengine.peer.*.mean, 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Messages Fetched",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "target": "aliasByNode(stats_counts.hubble.syncengine.peer_counts.*, 3, 4)"
    }
   ]
  },
  {
   "title": "Peer Scores",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 71 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.hubble.peer.*.score, 4)"
    }
   ]
  }
 ]
}